### PR TITLE
Patch for ImageMagick

### PR DESCRIPTION
**Pull request by Ayt3ck**
Hello, the choco package for ImageMagick does not uninstall the previous version on the latest update.
So I upgraded the verification and uninstall process.

I also add chocolateyUninstall to get a complete silent uninstall process.

Can you review and merge it if this patch works for you?

Best regards

### CODE REVIEW

**Review by bdukes — APPROVED** [review]
works for me, thanks!

**Comment by Ayt3ck** [comment]
Thanks @bdukes ,
can you rebuild the package offered at chocolatey to apply the patch?

**Comment by bdukes** [comment]
Done (in moderation)

**Comment by Ayt3ck** [comment]
Hello, it seems that the package is not yet in production, but I can't find it in moderation, has it been validated?

Best regard

**Comment by bdukes** [comment]
Thanks, I'd used the Chocolatey alpha to push, which apparently is broken so that it says the push succeeded when it doesn't. I've re-pushed and can see them in moderation now, e.g. https://community.chocolatey.org/packages/imagemagick.app/7.1.0.6001.

**Comment by Ayt3ck** [comment]
Thank, but it seem you forget to put source in :p

**Pull request merged**
