### PR TITLE
AU update: 11 updated

### PR DESCRIPTION
**Pull request by Thieum**
hg
imagemagick
imagemagick.app
imagemagic.tool
lastpass-for-applications
lastpass
linqpad5.anycpu.portable - beta
linqpad5.portable - beta

Woud be nice to push those on Chocolatey.org. Especially hg which is still on 4.6.1: https://chocolatey.org/packages/hg

Let me know if you need help for the publish.

### CODE REVIEW

**Comment by Thieum** [comment]
ah I see that hg 4.8.1 was submitted but failed the automated test somehow - I'll investigate:
https://chocolatey.org/packages/hg/4.8.1

**Comment by Thieum** [comment]
hmm both 4.8.1 and 4.8.2 work in the test environment provided in https://github.com/chocolatey/chocolatey-test-environment

**Comment by bdukes** [comment]
Thanks, https://chocolatey.org/packages/hg/4.8.2 has been submitted, and it's now marked to bypass validation (b/c of #25/#26), and it looks like 4.8.1 was accepted, also.

**Comment by bdukes** [comment]
I really appreciate you taking the initiative to look into that issue and get it moving and ultimately fixed.  I need to find some time to figure out why my automated update isn't working so that I don't need reminders to keep these up-to-date, but appreciate the help until then 😄

**Pull request closed without merging**
