### PR TITLE
Make the description and summary more clear, clean up chars.

### PR DESCRIPTION
**Pull request by altimmons**

### CODE REVIEW

**Comment by altimmons** [comment]
Oops i thought it let me merge.

**Comment by bdukes** [comment]
Thanks for calling this out!  I've added a clarifying statement into each package referring to the differences (46800ed).  

My opinion regarding the ® and © characters is that they display correctly on the Chocolatey website and in the Chocolatey GUI, so the display from the CLI is maybe a bug in the CLI, rather than something that should change in this package.

I'll go ahead and close this PR, let me know if you see anything more you think needs to be clarified or changed.

**Comment by altimmons** [comment]
Yea , I did fully consider that. And in general I agree. But I tried with 3 CLI processors and the new terminal on windows, and in all 3 cases for me, using 3 different fonts, it appended an “r” to the end of the word (eg “imagemagikr” which is generally confusing. It could be isolated to a setting I haven’t thought of on my single machine- it was my laptop I was on last night and not my full dev PC which has more of all those plugins, settings, dlls and what not. So there’s that. I added my best guess as to the difference between tool and app but if you are more clear on it, please feel free.  I just know I’m familiar with im and GM and was confused. (Familiar, though no expert. The syntax I often find bizarre and inconsistent which limits my use. )
Anyway, thanks for supplying these on choco. 

I also went through your box setup script, (Your work seems to go in a bit different direction than mine) and while I didn’t use it , I discovered several other useful programs to use. 

Regards,
Andy

**Comment by bdukes** [comment]
Thanks Andy.  Glad the setup script was helpful for you 😄 

I think the `®` vs `r` change is a bug in Chocolatey itself.  As far as I can tell, it seems to be instructing the shell to render an `r` (even though my shell, at least, is perfectly capable of rendering `®`).

**Pull request closed without merging**
